spring:
  application:
    name: myProducts

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs 
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
    operationsSorter: method
